// Known captures from https://zed.dev/docs/extensions/languages#syntax-highlighting
// and crates/grammars/src/**/highlights.scm at Zed revision:
// https://github.com/zed-industries/zed/tree/74646bf29c1a3d1cdb178930d810ecc5a8a6bece
// Dotted parent scopes are included because Zed uses them as fallbacks.
// Zed permits custom captures; add verified extension-specific names here as needed.
export const syntaxKeys = [
	"attribute",
	"attribute.builtin",
	"attribute.jsx",
	"attribute.special",
	"boolean",
	"comment",
	"comment.doc",
	"concept",
	"constant",
	"constant.builtin",
	"constructor",
	"diff",
	"diff.delta",
	"diff.delta.moved",
	"diff.minus",
	"diff.plus",
	"embedded",
	"emphasis",
	"emphasis.markup",
	"emphasis.strong",
	"emphasis.strong.markup",
	"enum",
	"function",
	"function.builtin",
	"function.call",
	"function.decorator",
	"function.decorator.call",
	"function.definition",
	"function.kwargs",
	"function.method",
	"function.method.call",
	"function.method.constructor",
	"function.special",
	"function.special.definition",
	"hint",
	"keyword",
	"keyword.control",
	"keyword.declaration",
	"keyword.definition",
	"keyword.directive",
	"keyword.import",
	"keyword.jsdoc",
	"keyword.operator",
	"keyword.operator.regex",
	"keyword.preproc",
	"label",
	"label.regex",
	"lifetime",
	"link_text",
	"link_text.markup",
	"link_uri",
	"link_uri.markup",
	"markup",
	"markup.heading",
	"markup.link",
	"markup.link.url",
	"module",
	"namespace",
	"nested",
	"none",
	"number",
	"number.quantifier",
	"number.quantifier.regex",
	"operator",
	"operator.regex",
	"operator.spaceship",
	"predictive",
	"preproc",
	"primary",
	"property",
	"property.json_key",
	"property.name",
	"punctuation",
	"punctuation.bracket",
	"punctuation.bracket.jsx",
	"punctuation.bracket.regex",
	"punctuation.delimiter",
	"punctuation.delimiter.jsx",
	"punctuation.delimiter.regex",
	"punctuation.embedded",
	"punctuation.embedded.markup",
	"punctuation.list_marker",
	"punctuation.list_marker.markup",
	"punctuation.markup",
	"punctuation.special",
	"selector",
	"selector.class",
	"selector.id",
	"selector.pseudo",
	"strikethrough",
	"strikethrough.markup",
	"string",
	"string.doc",
	"string.escape",
	"string.escape.regex",
	"string.regex",
	"string.special",
	"string.special.path",
	"string.special.symbol",
	"tag",
	"tag.component",
	"tag.component.jsx",
	"tag.doctype",
	"tag.jsx",
	"text",
	"text.jsx",
	"text.literal",
	"text.literal.markup",
	"title",
	"title.markup",
	"type",
	"type.builtin",
	"type.class",
	"type.class.builtin",
	"type.class.call",
	"type.class.definition",
	"type.class.inheritance",
	"type.definition",
	"type.interface",
	"type.jsdoc",
	"type.name",
	"type.unit",
	"variable",
	"variable.builtin",
	"variable.jsdoc",
	"variable.other",
	"variable.other.member",
	"variable.parameter",
	"variable.special",
	"variant",
] as const

export type SyntaxKey = (typeof syntaxKeys)[number]

const knownKeys: ReadonlySet<string> = new Set(syntaxKeys)

export function isSyntaxKey(key: string): key is SyntaxKey {
	return knownKeys.has(key)
}
